### PR TITLE
Fixing aXe spelling

### PR DESCRIPTION
**Pull request by aarongustafson**

### CODE REVIEW

**Comment by alrra** [comment]
@aarongustafson Can you sign the CLA? Thanks!

**Comment by alrra** [comment]
@aarongustafson I just realized this PR needs to be done against: https://github.com/sonarwhal/sonar/blob/master/docs/about/FAQ.md.  Can you open it in the other repository? Thanks!

**Comment by alrra** [comment]
@aarongustafson Fixed in https://github.com/sonarwhal/sonar/commit/22f2e1816e8d200fa3ccaf0871c1f260ecbcc316.

---

Note: You should update the content from your repository.

**Comment by aarongustafson** [comment]
Signed.

**Pull request closed without merging**
