### PR TITLE
New: Under construction page

### PR DESCRIPTION
**Pull request by ststimac**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests/#commitmessages)

## Short description of the change(s)

Page letting users know there is some maintenance happening so the service is unavailable.

@sarvaje here is your page for when the service is down.

### CODE REVIEW

**Comment by sarvaje** [comment]
LGTM, but the svg has dissapeared.

**Comment by alrra** [comment]
> but the svg has dissapeared.

Working in reducing it. :)

**Comment by alrra** [comment]
The SVG losslessly optimized:

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 475.1 489.4"><style>.a{fill:#9198cc;stroke:#2b2b2b;stroke-width:.25;stroke-miterlimit:10}.b{fill:#221f1f}.c{fill:#fff}.d{fill:#d6d9ed;stroke:#2b2b2b;stroke-width:.25}.d,.e,.f,.g{stroke-miterlimit:10}.e{stroke-linecap:round;stroke-linejoin:round;stroke-width:.25;fill:none;stroke:#6b6b6b}.f,.g{fill:#ffd833;stroke:#686868;stroke-width:.5}.g{fill:#d0d2d3}</style><path d="M159 171.9c74.1-7.2 140.6 52.7 148.5 133.8.6 6.5.8 12.9.7 19.3a120.4 120.4 0 0 1 48.4 32.6c12.4-5.3 23.8-8.8 33.4-10.1l-.3-.5-3.9-6.6-1.6-2.6c-6-10.2-.8-24.6 11.5-31.9l15.6-9.2c1.3-.8 2.8-.5 3.4.6l15.3 25.9c3.9 6.7 2.5 15.3-2.8 22.1l.2.4c8.5-1.4 16.7 1.5 20.7 8.2l15.3 25.9c.6 1.1.1 2.5-1.2 3.3l-15.6 9.2c-12.4 7.3-27.4 4.9-33.5-5.4l-2.8-4.8c-8 12.6-22.9 28.1-40.8 41.8-4.7 3.6-8.6 6.1-13.9 9.6a240 240 0 0 1-135.9 40.4c-32.4 0-62.4-5.7-87-15.2a132.6 132.6 0 0 1-28.8-14.7l-4.9-3.4-1.2-1-2.8-2.2a153.6 153.6 0 0 1-56-105.5c-7.8-81.2 45.8-152.8 120-160z" class="a"/><ellipse cx="199.9" cy="246.9" class="b" rx="8.5" ry="7.4"/><circle cx="198.4" cy="246" r="1.5" class="c"/><ellipse cx="106.3" cy="246.9" class="b" rx="8.5" ry="7.4"/><circle cx="108" cy="246" r="1.5" class="c"/><path d="M151.5 288.1c96.3 0 115.8 86.4 115.8 86.4 64.5 14.7 102 49.6 102 49.7a237.3 237.3 0 0 1-59.5 33.6 240 240 0 0 1-89.9 16.4c-32.4 0-62.4-5.7-87-15.2a132.6 132.6 0 0 1-28.8-14.7l-4.9-3.4-1.2-1-2.8-2.2a152.6 152.6 0 0 1-54.3-93.1c.6-3.4 16.5-56.5 110.6-56.5z" class="d"/><path fill="none" stroke="#1a1a1a" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width=".8" d="M162.7 272.4a16.7 16.7 0 0 1-19.6.2l-.3-.2"/><path fill="#3b5ca9" d="M252.9 342.6s-33.6 19-49.9-4.5a3.8 3.8 0 0 1 1.4-5.6l38.5-19.7"/><path d="M120.7 15.2L147.6 207l1.4 10.3c5.8 4.6 13.9 3.8 19.5.5l.9-.5-48.7-202.1z" class="d"/><path d="M169.6 217.4s-17.9-1.5-22.1-11.3m17.1-5.4c-5.1-.8-16.2-3.5-19.4-10.9m16.4-5.3c-5.4-1-15.5-3.7-18.6-10.8m13.8-6.6c-5.6-1.3-13.6-4.2-16.2-10.3m12.2-6.7c-5.4-1.5-11.9-4.3-14.2-9.8m10.8-6.5c-5.3-1.5-11.2-4.3-13.5-9.6m9.4-7.5c-4.7-1.6-9.5-4.4-11.5-8.9m7.4-8.1c-4.1-1.7-8-4.3-9.7-8.2m5-9.5c-3-1.6-6.3-5-7.6-8m-2.2-16.3c1 2.3 3.7 5.2 5.8 6.6" class="e"/><path d="M39.3 333s-35.4-15.5-26.4-42.6a3.8 3.8 0 0 1 5.3-2.3l41.1 20.1" class="a"/><path d="M171.8 151.5c-40.9 0-76.6 22.2-95.7 55.3h191.5a110.6 110.6 0 0 0-95.8-55.3z" class="f"/><path d="M266.4 213.7H77.2a5.8 5.8 0 0 1-5.7-5.7v-.8c0-3.1 2.6-5.7 5.7-5.7h189.2c3.1 0 5.7 2.6 5.7 5.7v.8c0 3.2-2.6 5.7-5.7 5.7z" class="f"/><path fill="#efc307" stroke="#686868" stroke-miterlimit="10" stroke-width=".5" d="M160.8 201.6h-25.3l-1.5-51.5h37.5z"/><defs><path id="h" d="M169.2 150.5c1 4.6-6.2 12.5-16.2 14.6-10 2.1-19.2-2.4-20.1-7s6.4-10 16.4-12.2c10-2 18.9 0 19.9 4.6z"/></defs><clipPath id="i"><use overflow="visible" xlink:href="#h"/></clipPath><g clip-path="url(#i)"><path d="M120.7 15.2L147.6 207l1.4 10.3c5.8 4.6 13.9 3.8 19.5.5l.9-.5-48.7-202.1z" class="d"/><path d="M169.6 217.4s-17.9-1.5-22.1-11.3m17.1-5.4c-5.1-.8-16.2-3.5-19.4-10.9m16.4-5.3c-5.4-1-15.5-3.7-18.6-10.8m13.8-6.6c-5.6-1.3-13.6-4.2-16.2-10.3m12.2-6.7c-5.4-1.5-11.9-4.3-14.2-9.8m10.8-6.5c-5.3-1.5-11.2-4.3-13.5-9.6m9.4-7.5c-4.7-1.6-9.5-4.4-11.5-8.9m7.4-8.1c-4.1-1.7-8-4.3-9.7-8.2m5-9.5c-3-1.6-6.3-5-7.6-8m-2.2-16.3c1 2.3 3.7 5.2 5.8 6.6" class="e"/></g><path fill="none" stroke="#000" stroke-miterlimit="10" stroke-width=".3" d="M141.6 164.9s7.5 2.1 15-.8"/><path d="M181 317.1s10.7-5.9 15.5-.7l5.8-5.4s-7-8.9-2.6-13.1c4.5-4.2 16.9-6.8 20.6-7.7 0 0-17.2-4.6-24.7.5l-.2.2a61.4 61.4 0 0 0-18.5 20.1l-.7 1.3 4.8 4.8z" class="g"/><path d="M184.7 321.1l-6.4 6-10.7-11.3 6.4-6zm30.8 17.1l7.2-6.8-20.4-20.4-5.8 5.4z" class="g"/><path fill="#404041" stroke="#686868" stroke-miterlimit="10" stroke-width=".5" d="M250.9 369.4l.5-.5a5 5 0 0 0 .2-7.1l-29.1-31.1-7.9 7.4 29.1 31.1c2 2 5.2 2.1 7.2.2z"/><path d="M255.1 341.7s-33.6 19-49.9-4.5a3.8 3.8 0 0 1 1.4-5.6l40.1-21.4" class="a"/></svg>
```

**Comment by sarvaje** [comment]
@molant, @ststimac, @alrra can you take a look to this?

**Comment by molant** [comment]
LGTM

**Pull request closed without merging**
