### PR TITLE
Fixes #286: URL wraps on mobile

### LINKED ISSUE #286: Scanned URL breaks layout on small viewports
Scanned URL:  https://sonarwhal.com/scanner/f32ced4f-df43-42a9-bdb5-6ae7ae7a4fcf

e.g. Edge on Android

### PR DESCRIPTION
**Pull request by TejasQ**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonar)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests.html#commitmessages) <- FYI, link is broken. Shall I open an issue?

## Short description of the change(s)
I made the word-wrap `break-word` so that the URL doesn't overflow.

### CODE REVIEW

**Comment by TejasQ** [comment]
@molant, will do. In the mean time, can this be merged?

**Comment by TejasQ** [comment]
[PR, as promised](https://github.com/sonarwhal/sonarwhal.com/pull/288)

**Comment by molant** [comment]
@TejasQ commit message should be something similar to:
```
Fix: URL wraps on mobile

Add `break-word` so the URL doesn't overflow.

Fix #286

**Comment by molant** [comment]
Thanks a lot @TejasQ !

**Comment by alrra** [comment]
Thanks, @TejasQ! 💜

**Pull request merged**
