### PR TITLE
Fix: Documentation title lengths

### LINKED ISSUE #441: Titles in documentation could take more space
They break really soon on wide screens even though the content goes further:

image

### PR DESCRIPTION
**Pull request by ststimac**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)
Makes page heading width larger

Fix #441
Close #441

### CODE REVIEW

**Comment by molant** [comment]
@ststimac can you make the body of the article wider as well? Most of the code examples need a scrollbar:

image

Having something like the following will be ideal:

image

**Comment by molant** [comment]
I think my biggest problem is the alignment of all the elements together.
We have the header and the "edit | signal issue" that end at one point and the text at another. Maybe we can increase the size of the text to stay under reasonable limits, the width of the navigation bar (and text size) or maybe we just need to revisit a bit the layout.

**Comment by ststimac** [comment]
Documentation content by nature isn't going to necessarily align all the way to the right for readability alone. The main priority of the documentation pages should be to deliver content in a readable way, so whether or not it extends all the way to the right side of the page or not is more of an aesthetic issue. 

I can bump up the paragraph width to 74rem though. That's still an acceptable length with the font size and it should conform to WCAG 2.0 guideline around line lengths for accessibility. 

Instead of having the edit & signal issue buttons at the top, what if I made them position: sticky and put them into their own tool box that scrolls with the user on the right side as they scroll down the page.  That would make it more user friendly too, as people scroll through, and find something they'd like to edit/suggest, they buttons will be right there and they don't have to scroll back to the top.

**Comment by molant** [comment]
Another option is to reduce the width of the header. In any case, paste whenever you are ready an image of how it would look like.

Thanks!

**Comment by ststimac** [comment]
@molant let's not reduce the width of the header. That will take more work than I think is necessary.

**Comment by molant** [comment]
> Can we open a new issue

Sure, open it.

**Comment by ststimac** [comment]
@molant this one will only change title length, separate one to come for the other updates to the page.

**Comment by molant** [comment]
And is it finished or do you want to do something else?

**Comment by ststimac** [comment]
This is done.

**Pull request merged**
