### PR TITLE
Documentation Landing Page

### PR DESCRIPTION
**Pull request by ststimac**
@qzhou1607 we have a new css file for documentation. Can we have it pulled in only for the documentation pages, landing page included?

@alrra it looks like my commits from my other PR for search results were pulled into this PR. How can I fix this?

### CODE REVIEW

**Comment by alrra** [comment]
> it looks like my commits from my other PR for search results were pulled into this PR. How can I fix this?

@ststimac Should be fixed.

**Comment by qzhou1607** [comment]
@ststimac Can you fix the errors in the css file running lint?

**Comment by ststimac** [comment]
@qzhou1607 sorry, yes, should be fixed now.

**Comment by qzhou1607** [comment]
@ststimac @alrra Done.

**Comment by molant** [comment]
@qzhou1607 can you please squash all these commits and add a new one following the convention of the other repo?

**Comment by qzhou1607** [comment]
@molant Done. I didn't realize that this page includes a search bar, so it will be best to merge this PR after I'm done with https://github.com/sonarwhal/sonarwhal.com/pull/164. Also @ststimac I tried to fix the mixed files from the other PR, can you double check the current commit to see if it looking okay?

**Comment by molant** [comment]
@qzhou1607 #164 is merged now. Can you fix the conflicts and update this PR please?

**Comment by qzhou1607** [comment]
@molant Done.

**Pull request closed without merging**
