### PR TITLE
Fix: Fix menu and treeviews

### LINKED ISSUE #180: Menu and treeviews in sonar website are not working

### PR DESCRIPTION
**Pull request by qzhou1607**
I can't reproduce this problem in local. But it looks like that the minifier has trouble finding the js files in travis. The `contributors.md` change is a change before that didn't get merged for some reason.
 
Fix #180

### CODE REVIEW

**Comment by qzhou1607** [comment]
Just tried switching versions of `hexo-all-minifier` between `0.2.0` and `0.1.1`. The `0.2.0` version causes error in js rendering and I was able to reproduce the error in local. So in this PR I put the version back to `0.1.1`.

**Comment by molant** [comment]
We should still find out why 0.2.0 doesn't work.

**Comment by qzhou1607** [comment]
@molant It's an issue in the latest version of the minifier. `uglify-es` was used to replace `utlify-js`, and a parameter passed in `hexo-all-minifier` becomes incorrect after this switch. I opened an issue at https://github.com/chenzhutian/hexo-all-minifier/issues/28 and we can update to the latest version once that is fixed in the release.

**Comment by alrra** [comment]
>  It's an issue in the latest version of the minifier.

It [has been fixed](https://github.com/chenzhutian/hexo-all-minifier/issues/28#issuecomment-320388989). 🎉

**Pull request closed without merging**
