### PR TITLE
Fix: Favicon status icon size

### LINKED ISSUE #265: Make scanner indicate scan state using the favicon
GitHub recently added something similar, and personally, I think it's a great idea.

(from https://twitter.com/left_pad/status/922905320543760384?s=03)

### PR DESCRIPTION
**Pull request by ststimac**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests/#commitmessages)

## Short description of the change(s)

Fix #265

Adjusted the size of the status icons. Let's see if this makes any improvement otherwise I'll have to modify further. Maybe change the color of the whole icon but want to make that a last resort because some of the status colors may not have enough contrast against the browser tab depending on user settings.

### CODE REVIEW

**Comment by alrra** [comment]
@sarvaje Can you post a picture with how it looks? Thanks!

**Comment by molant** [comment]
@alrra I guess you meant @ststimac ?

**Comment by alrra** [comment]
> I guess you meant @ststimac ?

Yeap, GitHub autocomplete fail.

**Comment by ststimac** [comment]
favicons
screen shot 2018-01-10 at 3 30 28 pm

**Pull request merged**
