### PR TITLE
clean up contributors page

### PR DESCRIPTION
**Pull request by ststimac**
This will fix the alignment and some of the spacing &  width issues for the time being.

### CODE REVIEW

**Comment by alrra** [comment]
@ststimac There is [a linting problem](https://travis-ci.org/sonarwhal/sonarwhal.com#L543).  Can you fix it? Also, can you attach a screenshot with how it looks now? Thanks!

**Comment by ststimac** [comment]
screen shot 2017-06-26 at 11 34 50 am

as a side note, npm test didn't catch that error with the unnecessary 0 and these are the errors showing up that @molant told me to disregard. :(

screen shot 2017-06-26 at 11 35 47 am

**Comment by molant** [comment]
Can we add the missing people?

**Comment by molant** [comment]
@alrra the listing errors come from sonar. We should fix them there and/or make sure the markdown lint rules are the same.

**Comment by ststimac** [comment]
@molant one of the errors was in my code but when I ran npm test it didn't catch it :/

**Comment by alrra** [comment]
> We should fix them there and/or make sure the markdown lint rules are the same.

I'll take care of that later today.

---

@ststimac Notes: In the future

* Start your commit message with an uppercase letter.
* Add at the end of the commit message `Fix #<issue_number_the_pr_fixes>`

**Comment by alrra** [comment]
> We should fix them there and/or make sure the markdown lint rules are the same.

@molant Fixed in https://github.com/sonarwhal/sonarwhal.com/commit/7429504822b7e88347a13492ed68ae9a58572a88.

**Pull request closed without merging**
