### PR TITLE
Fix: ToC treeview arrow gets bumped to next line

### LINKED ISSUE #326: Arrow bumped to the next line in treeview
The arrow gets bumped to the next line:

arrow

### PR DESCRIPTION
**Pull request by ststimac**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests/#commitmessages)

## Short description of the change(s)

Fix #326 

Arrow should no longer be bumped to next line

### CODE REVIEW

**Comment by alrra** [comment]
Issue is still present for me :(

**Comment by ststimac** [comment]
@alrra what browser?

**Comment by alrra** [comment]
Firefox/Chrome/etc. on macOS

**Comment by ststimac** [comment]
It's all still showing as fixed for me on mac os. Can you inspect and tell me what properties are showing under these class names:` .toc-section-title, .toc-section-title--active `

**Comment by alrra** [comment]
See: 

* [`.toc-section-title`](https://user-images.githubusercontent.com/1223565/34133224-72332578-e408-11e7-951e-89193d6e192c.png)
* [`.toc-section-title--active`](https://user-images.githubusercontent.com/1223565/34133225-724921de-e408-11e7-96eb-bfb5e5362d0a.png)

**Comment by ststimac** [comment]
Are you running the most up to date versions of the browsers? I assume so but I'm not sure what's happening right now because the CSS class properties are correct so trying to eliminate possibilities.

**Comment by ststimac** [comment]
Hrmmm, ok, I can repro on Windows. The fix isn't working there in edge, firefox and chrome. Will have to investigate more.

**Pull request closed without merging**
