### PR TITLE
Remove line from above headings

### PR DESCRIPTION
**Pull request by alrra**
Personally, I don't see the point of having it.

### CODE REVIEW

**Comment by molant** [comment]
O guess this is more a stetic issue to separate sections than anything else so it should be up to @ststimac unless there is another problem I'm not seeing.

**Comment by ststimac** [comment]
@molant @alrra  yes, this is to help separate sections and identify the the main section title & should be kept.

**Comment by alrra** [comment]
> & should be kept.

@ststimac Would you reconsider this? IMHO, it looks very out of place (e.g.: https://sonarwhal.com/about/changelog.html).

**Comment by ststimac** [comment]
@alrra I was going to add some iconography/custom styling to Changelog. So those headings most likely won't have the lines above.

**Comment by alrra** [comment]
> I was going to add some iconography/custom styling to Changelog. So those headings most likely won't have the lines above.

**Pull request closed without merging**
