### PR TITLE
Fix: Add table styles

### LINKED ISSUE #404: Table format doesn't look right
Go to https://sonarwhal.com/docs/user-guide/rules/rule-performance-budget/#can-the-rule-be-configured

This is how it looks in Edge:

image

### PR DESCRIPTION
**Pull request by ststimac**
Fix #404
Close #404

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)

Adds table styling.

table-styling

### CODE REVIEW

**Comment by molant** [comment]
@ststimac aren't the headers too small compared to the rest of the table (or even the text above that's not part of it) in the document?

image

**Comment by ststimac** [comment]
That's pretty standard for tables. Usually the column labels are smaller. I can bump it up a point if you have a problem with it.

**Comment by molant** [comment]
Yes, having something more obvious will be great. Maybe follow what GitHub and spreadsheet tools do with table formatting: 

| Value | In | Out | RTT | 
| -----| -------| -----| -------|
| FIOS    | 20 Mbps | 5 Mbps | 4 ms |
| LTE | 12 Mbps | 12 Mbps | 70 ms |

**Comment by ststimac** [comment]
You want actual borders in the table?

**Comment by molant** [comment]
I was thinking more about same font size header but bolder. Don't have any opinion about borders TBH.

**Comment by ststimac** [comment]
No borders! I am against borders. 

Font update is fine.

**Comment by ststimac** [comment]
table-styling-2

**Comment by molant** [comment]
Awesome, can you remove `categories.json` from the commit?

**Comment by ststimac** [comment]
Done

**Pull request merged**
