### PR TITLE
New: Add GDPR banner

### LINKED ISSUE #427: Need banner telling people we use cookies
Text: 

> This site uses cookies for analytics. By continuing to browse this site, you agree to this use.

And we will initialize GA if the user closes the banner, navigates, or clicks somewhere.

@ststimac I'll start working on something and I'll let you review the styles once the logic is done.

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests/#commitmessages)

## Short description of the change(s)

Fix #427 

This still needs some modifications from @ststimac to make it look ok. Or change styles if needed. Right now it looks like this:

image

### CODE REVIEW

**Comment by molant** [comment]
@ststimac all yours. IMO, just fixing the button should be enough to merge this. Don't know why it looks broken though :(
Let me know if you want to take a quick look in my computer so you don't have to pull the code.

**Comment by ststimac** [comment]
@molant it looks like there are some JS errors. 

Did you want me to add the "min-width" & make the adjustments to the button?

**Comment by molant** [comment]
> Did you want me to add the "min-width" & make the adjustments to the button?

Nope, had to leave early today and didn't push the changes.

**Comment by molant** [comment]
Updated the code and this is how it looks like now:

image

I'll be merging this soon-ish unless someone has something strongly agains it.

**Pull request closed without merging**
